version: '3.8'

services:
  # NestJS Backend (Cloud Run compatible)
  backend:
    build:
      context: ./Backend/nest-backend
      dockerfile: Dockerfile
      target: production
    container_name: rict-backend-cloudrun
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - rict-network-cloudrun
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Angular Frontend (Cloud Run compatible)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      target: production
    container_name: rict-frontend-cloudrun
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - rict-network-cloudrun
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  rict-network-cloudrun:
    driver: bridge
